#pragma once

using namespace ATL;

template <class T>
class CProxy_IsampleIfcEvents : public IConnectionPointImpl<T, &__uuidof( _IsampleIfcEvents ), CComDynamicUnkArray>
{
	// WARNING: This class may be regenerated by the wizard
public:
};
